angular.module('Realize.reporting', [
    'Realize.common.DateRangeSelector',
    'Realize.reporting.ReportService',
    'Realize.reporting.MasteryByStandardReport',
    'Realize.reporting.MasteryByAssignmentService',
    'Realize.reporting.LineGraph',
    'Realize.reporting.BarGraph',
    'Realize.reporting.CategoryBarGraph',
    'Realize.reporting.friendlyTimeFilter',
    'Realize.reporting.friendlyTime',
    'Realize.reporting.data.UsageRecapCtrl',
    'Realize.reporting.data.TrackingService',
    'Realize.reporting.data.DataClassOverviewCtrl',
    'Realize.reporting.data.DataCtrl',
    'Realize.reporting.data.MasteryCtrl',
    'Realize.reporting.data.MasteryStandardCtrl',
    'Realize.reporting.data.IndividualStudentReportCtrl',
    'Realize.reporting.data.ProgressCtrl',
    'Realize.reporting.data.masteryByStandardsFilters',
    'Realize.reporting.data.ItemAnalysisCtrl',
    'Realize.reporting.grades.GradesHomeCtrl',
    'Realize.reporting.grades.GradesOverviewCtrl',
    'Realize.reporting.grades.StudentProgressRecapCtrl',
    'Realize.reporting.grades.StudentItemAnalysisCtrl',
    'Realize.reporting.grades.StudentItemAnalysisSvc',
    'Realize.reporting.data.DiagnosticAssessmentReportCtrl',
])
.constant('MASTERY_NAME_MAXLENGTH', 18)
.constant('MASTERY_THRESHOLD', 0.7);
