angular.module('Realize.constants.googleClassroom', [])
    .constant('GOOGLE_CLASSROOM', {
        SIZE: '18',
        THEME: 'light',
        SHOW_GOOGLE_CLASSROOM_INTEGRATION: 'show.google.classroom.integration',
        ROSTER_SOURCE: {
            GOOGLE_CLASSROOM: 'google'
        },
        SYNC_SUCCESS_TIMEOUT: 10000,
        SYNC_SUCCESS: 'success',
        SYNC_IN_PROGRESS: 'inProgress',
        SYNC_COMPLETED: 'Completed',
        ASSIGNMENT_LIST: 'Assignment List',
        ASSIGNMENT_DETAIL: 'Assignment Detail',
        GET_STARTED: 'Get Started',
        SETTINGS: 'Settings',
        ACCOUNT_LINKING: 'Account Linking',
        GOOGLE_GET_STARTED: 'Google - Get Started',
        CONNECT_CLASS: 'Import Class',
        GOOGLE_CONNECT: 'Google - Connect',
        EDIT_CLASS_SETTINGS: 'Edit Class Settings',
        GOOGLE_EDIT_CLASS: 'Google - Edit Class',
        DATA: 'Data',
        OPEN: 'Open',
        DISCONNECT: 'Disconnect',
        DISCONNECT_ACCOUNT: 'Disconnect Account',
        GOOGLE_DISCONNECT_ACCOUNT: 'Google - Disconnect Account',
        HOME: 'Home',
        DELETED: 'DELETED',
        ARCHIVED: 'ARCHIVED',
        DELETED_LOWERCASE: 'deleted',
        ARCHIVED_LOWERCASE: 'archived',
        ACTIVE: 'ACTIVE',
        HIDDEN: 'hidden',
        UNARCHIVE: 'Unarchive',
        UNARCHIVE_CLASS: 'Unarchive Class',
        GOOGLE_UNARCHIVE: 'Google - Unarchive',
        ACCOUNT_REVOKED_STATUS_CODE: 412,
        EXTERNAL_ERROR: 'External'
    });
