angular.module('Realize.constants.mediaType', [
])
.constant('MEDIA_TYPE', {
    DISCUSSION_PROMPT: 'Discussion Prompt',
    ADAPTIVE_HOMEWORK: 'Adaptive Homework',
    DIAGNOSTIC_ASSESSMENT: 'Diagnostic Assessment',
    SELECTED_READING: 'Selected Reading',
    LEVELED_READER: 'Leveled Reader',
    PARTNER_LINK: 'Partner Link',
    LEARNING_MODEL: 'Learning Model',
    STUDENT_VOICE: 'Student Voice',
    INTERACTIVE_MEDIA: 'Interactive Media',
    LINK: 'Link',
    TEST: 'Test',
    AUDIO: 'Audio',
    VIDEO: 'Video',
    ETEXT: 'eText',
    REALIZE_READER_SELECTION: 'Realize Reader Selection',
    QUESTION_BANK: 'Question Bank',
    DOCUMENT: 'Document',
    NOT_AVAILABLE: 'notavailable',
    ACTIVITY_SUPPORT: 'Activity Support',
    LESSON: 'Lesson',
    TIER: 'Tier',
    CONTENT: 'content',
    REMEDIATION: 'Remediation',
    PLAYLIST: 'Playlist',
    DESMOS: 'Desmos',
    NOTATION: 'Notation',
    CENTER_CONTAINER: 'Center Container',
    LEARNING_RESOURCE: 'Learning Resource',
    GOOGLE_DOC: 'Google Doc'
});
